n = str(input('digite um numero  '))
print ('o milhar nesse numero é {}'.format(n[0]))
print ('a centena nesse numero é {}'.format(n[1]))
print ('a dezena nesse numero é {}'.format(n[2]))
print ('a unidade nesse numero é {}'.format(n[3]))
